apiVersion: s3.radosgw.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: my-test-buck-fff
spec:
  forProvider:
    externalBucketName: my-test-buck-fff
    locationConstraint: default
    cephUserUID: testuser-crossplane-f
  providerConfigRef:
    name: ceph-admin-cfg