apiVersion: s3.radosgw.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: my-test-buck-d
spec:
  forProvider:
    externalBucketName: my-test-buck-d
    locationConstraint: default
    cephUserUID: testuser-crossplane-d
  providerConfigRef:
    name: ceph-admin-cfg