apiVersion: ceph.radosgw.crossplane.io/v1alpha1
kind: CephUser
metadata:
  name: my-ceph-user-i
spec:
  deletionPolicy: Delete
  forProvider:
    displayedName: my-ceph-user-i
    uid: myuser-i
    userQuotaMaxBuckets: 5
    userQuotaMaxObjects: 1000
    userQuotaMaxSizeKB: 204800
  credentials:
    vault:
      address:
      kvVersion:
      path:
  providerConfigRef:
    name: ceph-nlzwo1o-e
