apiVersion: ceph.radosgw.crossplane.io/v1alpha1
kind: CephUser
metadata:
  name: my-ceph-user-b
spec:
  deletionPolicy: Delete
  forProvider:
    displayedName: my-ceph-user-b
    uid: myuser-b
    userQuotaMaxBuckets: 5
    userQuotaMaxObjects: 1000
    userQuotaMaxSizeKB: 204800
  providerConfigRef:
    name: ceph-nlzwo1o-c
