apiVersion: ceph.radosgw.crossplane.io/v1alpha1
kind: CephUser
metadata:
  name: my-ceph-user-x
spec:
  deletionPolicy: Delete
  forProvider:
    displayedName: my-ceph-user-x
    uid: myuser-x
    userQuotaMaxBuckets: 5
    userQuotaMaxObjects: 1000
    userQuotaMaxSizeKB: 204800
#  credentials:
#  credentials:
#    vault:
#      address:
#      kvVersion:
#      path:
  providerConfigRef:
    name: ceph-nlzwo1o-c
