apiVersion: ceph.radosgw.crossplane.io/v1alpha1
kind: CephUser
metadata:
  name: my-ceph-user
spec:
  deletionPolicy: Delete
  forProvider:
    displayedName: john_doe
    uid: johndoe123
    userQuotaMaxBuckets: 5
    userQuotaMaxObjects: 1000
    userQuotaMaxSizeKB: 204800
  providerConfigRef:
    name: ceph-admin-cfg
